server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /import-map-data {
        proxy_pass http://api:5000/import-map-data;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /maps {
        proxy_pass http://api:5000/maps;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /maps/ {
        proxy_pass http://api:5000/maps/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
        proxy_pass http://api:5000/health;
        proxy_set_header Host $host;
    }
}